version: "3.8"
services:
  3proxy-wireguard:
    build:
      context: .
      dockerfile: 3proxy.Dockerfile
    container_name: wireguard-bkk-3proxy
    restart: unless-stopped
    hostname: wireguard-bkk-3proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config/wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
      - ./custom-init-scripts:/custom-cont-init.d:ro
    ports:
      - 62820:51820/udp
      - 6667:6667
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      default:
        ipv4_address: 172.30.0.5

networks:
  default:
    name: vpn_network
    external: true