version: "3.8"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      # - PEERS=1
      # - PEERDNS=auto
    ports:
      - "51820:51820/udp" 
    volumes:
      - custom-init-scripts/custom-script.sh:/custom-cont-init.d:ro
      - /home/datvo/wiregruard/th-bkk.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    networks:
      default:
        ipv4_address: 172.20.0.50
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

networks:
  default:
    name: wireguard
    external: true