version: "3.8"
services:

  tinyproxy-wireguard-1:
    build:
      context: .
      dockerfile: tinyproxy.Dockerfile
    container_name: wireguard-bkk-tinyproxy
    restart: unless-stopped
    hostname: wireguard-bkk-tinyproxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config/wg0.conf:/config/wg0.conf
      - ./config/tinyproxy.conf:/tinyproxy/tinyproxy.conf
      - ./config/start-tinyproxy.sh:/start-tinyproxy.sh
      - ./logs/tinyproxy/:/var/log/tinyproxy/:rw,cached
      - /lib/modules:/lib/modules
      # - ./custom-init-scripts:/custom-cont-init.d:ro
    ports:
      - 62820:51820/udp
      - 8888:8888/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      default:
        ipv4_address: 172.30.0.4
  
  tinyproxy-wireguard-2:
      build:
        context: .
        dockerfile: tinyproxy.Dockerfile
      container_name: wireguard-san-tinyproxy
      restart: unless-stopped
      hostname: wireguard-san-tinyproxy
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Ho_Chi_Minh
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      volumes:
        - ./config/wg1.conf:/config/wg1.conf
        - ./config/tinyproxy.conf:/tinyproxy/tinyproxy.conf
        - ./config/start-tinyproxy.sh:/start-tinyproxy.sh
        - ./logs/tinyproxy/:/var/log/tinyproxy/:rw,cached
        - /lib/modules:/lib/modules
        # - ./custom-init-scripts:/custom-cont-init.d:ro
      ports:
        - 62821:51820/udp
        - 8889:8888/tcp
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
      networks:
        default:
          ipv4_address: 172.30.0.5

networks:
  default:
    name: vpn_network
    external: true